export const promo12 = {
  id: "1-2",
  title: "科学测评 洞悉天性 掌握人生",
  module: "认识自我 · 第 2 节",
  teacherName: "韩旭老师",
  teacherRole: "新知领导力合伙人",
    scenes: [
    {
      id: "opening",
      durationInFrames: 150,
      kicker: "认识自我核心内容",
      headline: "科学测评 洞悉天性 掌握人生",
      subline: "能够了解别人的人是有智慧的，能够认识自己的人是更高明的！",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#38bdf8",
      videoStartSeconds: 30,
      layout: "center",
    },
    {
      id: "point1",
      durationInFrames: 300,
      kicker: "核心内容",
      headline: "科学测评 洞悉天性 掌握人生",
      subline: "深入学习科学测评 洞悉天性 掌握人生，系统掌握职场能力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#38bdf8",
      videoStartSeconds: 60,
      layout: "center",
    },
    {
      id: "point2",
      durationInFrames: 300,
      kicker: "重点掌握",
      headline: "科学测评 洞悉天性 掌握人生",
      subline: "学完本节，你将获得实用方法论与关键技能。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#38bdf8",
      videoStartSeconds: 60,
      layout: "center",
    },
    {
      id: "path",
      durationInFrames: 240,
      kicker: "课程路径",
      headline: "科学测评 洞悉天性 掌握人生",
      subline: "从认识到实践，逐步构建职场竞争力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#38bdf8",
      videoStartSeconds: 48,
      layout: "path",
    },
    {
      id: "end",
      durationInFrames: 120,
      kicker: "认识自我",
      headline: "科学测评 洞悉天性 掌握人生",
      subline: "系统学习，打造不可替代的职场竞争力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#38bdf8",
      videoStartSeconds: 24,
      layout: "teacher",
    },
  ]
};

export const COURSE_PROMO_1_2_DURATION = 1110;
