export const promo51 = {
  id: "5-1",
  title: "人生升华",
  module: "人生升华 · 第 1 节",
  teacherName: "韩旭老师",
  teacherRole: "新知领导力合伙人",
    scenes: [
    {
      id: "opening",
      durationInFrames: 150,
      kicker: "人生升华核心内容",
      headline: "人生升华",
      subline: "首要问题就是路途遥远、沿途常有强盗出没，而且马匹的饲养和运输也需要专业知识和经验。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#fbbf24",
      videoStartSeconds: 30,
      layout: "center",
    },
    {
      id: "point1",
      durationInFrames: 300,
      kicker: "核心内容",
      headline: "人生升华",
      subline: "深入学习人生升华，系统掌握职场能力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#fbbf24",
      videoStartSeconds: 60,
      layout: "center",
    },
    {
      id: "point2",
      durationInFrames: 300,
      kicker: "重点掌握",
      headline: "人生升华",
      subline: "学完本节，你将获得实用方法论与关键技能。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#fbbf24",
      videoStartSeconds: 60,
      layout: "center",
    },
    {
      id: "path",
      durationInFrames: 240,
      kicker: "课程路径",
      headline: "人生升华",
      subline: "从认识到实践，逐步构建职场竞争力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#fbbf24",
      videoStartSeconds: 48,
      layout: "path",
    },
    {
      id: "end",
      durationInFrames: 120,
      kicker: "人生升华",
      headline: "人生升华",
      subline: "系统学习，打造不可替代的职场竞争力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#fbbf24",
      videoStartSeconds: 24,
      layout: "teacher",
    },
  ]
};

export const COURSE_PROMO_5_1_DURATION = 1110;
