export const promo216 = {
  id: "2-16",
  title: "# 改变自我",
  module: "改变自我 · 第 16 节",
  teacherName: "韩旭老师",
  teacherRole: "新知领导力合伙人",
    scenes: [
    {
      id: "opening",
      durationInFrames: 150,
      kicker: "改变自我核心内容",
      headline: "# 改变自我",
      subline: "高层在考虑提拔时，核心问题只有一个：“这个人能帮我解决什么问题？”",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#22c55e",
      videoStartSeconds: 30,
      layout: "center",
    },
    {
      id: "point1",
      durationInFrames: 300,
      kicker: "核心内容",
      headline: "# 改变自我",
      subline: "深入学习# 改变自我，系统掌握职场能力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#22c55e",
      videoStartSeconds: 60,
      layout: "center",
    },
    {
      id: "point2",
      durationInFrames: 300,
      kicker: "重点掌握",
      headline: "# 改变自我",
      subline: "学完本节，你将获得实用方法论与关键技能。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#22c55e",
      videoStartSeconds: 60,
      layout: "center",
    },
    {
      id: "path",
      durationInFrames: 240,
      kicker: "课程路径",
      headline: "# 改变自我",
      subline: "从认识到实践，逐步构建职场竞争力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#22c55e",
      videoStartSeconds: 48,
      layout: "path",
    },
    {
      id: "end",
      durationInFrames: 120,
      kicker: "改变自我",
      headline: "# 改变自我",
      subline: "系统学习，打造不可替代的职场竞争力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#22c55e",
      videoStartSeconds: 24,
      layout: "teacher",
    },
  ]
};

export const COURSE_PROMO_2_16_DURATION = 1110;
