export const promo11 = {
  id: "1-1",
  title: "人生趋势图：",
  module: "认识自我 · 第 1 节",
  teacherName: "韩旭老师",
  teacherRole: "新知领导力合伙人",
    scenes: [
    {
      id: "opening",
      durationInFrames: 150,
      kicker: "认识自我核心内容",
      headline: "人生趋势图：",
      subline: "目的：是让你读懂趋势，掌握人生各阶段关键时期的必备知识，甄选捷径，让你每一个阶段都有前进的方向！",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#38bdf8",
      videoStartSeconds: 30,
      layout: "center",
    },
    {
      id: "point1",
      durationInFrames: 300,
      kicker: "核心内容",
      headline: "人生趋势图：",
      subline: "深入学习人生趋势图：，系统掌握职场能力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#38bdf8",
      videoStartSeconds: 60,
      layout: "center",
    },
    {
      id: "point2",
      durationInFrames: 300,
      kicker: "重点掌握",
      headline: "人生趋势图：",
      subline: "学完本节，你将获得实用方法论与关键技能。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#38bdf8",
      videoStartSeconds: 60,
      layout: "center",
    },
    {
      id: "path",
      durationInFrames: 240,
      kicker: "课程路径",
      headline: "人生趋势图：",
      subline: "从认识到实践，逐步构建职场竞争力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#38bdf8",
      videoStartSeconds: 48,
      layout: "path",
    },
    {
      id: "end",
      durationInFrames: 120,
      kicker: "认识自我",
      headline: "人生趋势图：",
      subline: "系统学习，打造不可替代的职场竞争力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#38bdf8",
      videoStartSeconds: 24,
      layout: "teacher",
    },
  ]
};

export const COURSE_PROMO_1_1_DURATION = 1110;
