export const promo43 = {
  id: "4-3",
  title: "管理团队",
  module: "领导团队 · 第 3 节",
  teacherName: "韩旭老师",
  teacherRole: "新知领导力合伙人",
    scenes: [
    {
      id: "opening",
      durationInFrames: 150,
      kicker: "领导团队核心内容",
      headline: "管理团队",
      subline: "下面介绍超预期管理的实践应用，请你按照自身情况选择性借鉴学习:",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#f97316",
      videoStartSeconds: 30,
      layout: "center",
    },
    {
      id: "point1",
      durationInFrames: 300,
      kicker: "核心内容",
      headline: "管理团队",
      subline: "深入学习管理团队，系统掌握职场能力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#f97316",
      videoStartSeconds: 60,
      layout: "center",
    },
    {
      id: "point2",
      durationInFrames: 300,
      kicker: "重点掌握",
      headline: "管理团队",
      subline: "学完本节，你将获得实用方法论与关键技能。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#f97316",
      videoStartSeconds: 60,
      layout: "center",
    },
    {
      id: "path",
      durationInFrames: 240,
      kicker: "课程路径",
      headline: "管理团队",
      subline: "从认识到实践，逐步构建职场竞争力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#f97316",
      videoStartSeconds: 48,
      layout: "path",
    },
    {
      id: "end",
      durationInFrames: 120,
      kicker: "领导团队",
      headline: "管理团队",
      subline: "系统学习，打造不可替代的职场竞争力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#f97316",
      videoStartSeconds: 24,
      layout: "teacher",
    },
  ]
};

export const COURSE_PROMO_4_3_DURATION = 1110;
