export const promo21 = {
  id: "2-1",
  title: "__ 改变自我__",
  module: "改变自我 · 第 1 节",
  teacherName: "韩旭老师",
  teacherRole: "新知领导力合伙人",
    scenes: [
    {
      id: "opening",
      durationInFrames: 150,
      kicker: "改变自我核心内容",
      headline: "__ 改变自我__",
      subline: "模块2第1节",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#22c55e",
      videoStartSeconds: 30,
      layout: "center",
    },
    {
      id: "point1",
      durationInFrames: 300,
      kicker: "核心内容",
      headline: "__ 改变自我__",
      subline: "深入学习__ 改变自我__，系统掌握职场能力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#22c55e",
      videoStartSeconds: 60,
      layout: "center",
    },
    {
      id: "point2",
      durationInFrames: 300,
      kicker: "重点掌握",
      headline: "__ 改变自我__",
      subline: "学完本节，你将获得实用方法论与关键技能。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#22c55e",
      videoStartSeconds: 60,
      layout: "center",
    },
    {
      id: "path",
      durationInFrames: 240,
      kicker: "课程路径",
      headline: "__ 改变自我__",
      subline: "从认识到实践，逐步构建职场竞争力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#22c55e",
      videoStartSeconds: 48,
      layout: "path",
    },
    {
      id: "end",
      durationInFrames: 120,
      kicker: "改变自我",
      headline: "__ 改变自我__",
      subline: "系统学习，打造不可替代的职场竞争力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#22c55e",
      videoStartSeconds: 24,
      layout: "teacher",
    },
  ]
};

export const COURSE_PROMO_2_1_DURATION = 1110;
