export const promo0 = {
  id: "0",
  title: "永远不怕失业的能力",
  module: "代总序",
  teacherName: "韩旭老师",
  teacherRole: "新知领导力合伙人",
  scenes: [
    {
      id: "opening",
      durationInFrames: 150,
      kicker: "实务领导力 · 代总序",
      headline: "永远不怕失业的能力",
      subline: "让你摆脱职场焦虑，掌握领导者必备的能力，实现快速晋升。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#f59e0b",
      layout: "split",
    },
    {
      id: "point1",
      durationInFrames: 300,
      kicker: "时代之问",
      headline: "AI 时代，如何抵御失业？",
      subline: "在 ChatGPT、DeepSeek 颠覆行业的当下，唯有领导力，是无法被 AI 替代的核心能力。",
      keywords: ["AI", "趋势", "不可替代"],
      accent: "#f59e0b",
      layout: "center",
    },
    {
      id: "point2",
      durationInFrames: 300,
      kicker: "课程核心",
      headline: "拥有领导力，就拥有了永远不怕失业的能力。",
      subline: "韩旭老师亲授实务领导力，帮你从员工到一线经理，完成职业生涯最关键的一跃。",
      keywords: ["升职", "加薪", "圈层"],
      accent: "#f59e0b",
      layout: "quote",
    },
    {
      id: "path",
      durationInFrames: 240,
      kicker: "五大模块",
      headline: "完整的领导力成长路径",
      subline: "认识自我 · 改变自我 · 领导他人 · 领导团队 · 人生升华",
      keywords: ["认识自我", "改变自我", "领导他人", "领导团队", "人生升华"],
      accent: "#f59e0b",
      layout: "path",
    },
    {
      id: "end",
      durationInFrames: 120,
      kicker: "新知领导力合伙人",
      headline: "韩旭老师",
      subline: "人生没有专属的路线图，但你要有前进的指南针。",
      keywords: ["实务领导力", "代总序"],
      accent: "#f59e0b",
      layout: "teacher",
    },
  ],
};

export const COURSE_PROMO_0_DURATION = 1110;
