export const promo34 = {
  id: "3-4",
  title: "管理他人",
  module: "领导他人 · 第 4 节",
  teacherName: "韩旭老师",
  teacherRole: "新知领导力合伙人",
    scenes: [
    {
      id: "opening",
      durationInFrames: 150,
      kicker: "领导他人核心内容",
      headline: "管理他人",
      subline: "所以，你要了解和利用衡量过的职场关系",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#a78bfa",
      videoStartSeconds: 30,
      layout: "center",
    },
    {
      id: "point1",
      durationInFrames: 300,
      kicker: "核心内容",
      headline: "管理他人",
      subline: "深入学习管理他人，系统掌握职场能力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#a78bfa",
      videoStartSeconds: 60,
      layout: "center",
    },
    {
      id: "point2",
      durationInFrames: 300,
      kicker: "重点掌握",
      headline: "管理他人",
      subline: "学完本节，你将获得实用方法论与关键技能。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#a78bfa",
      videoStartSeconds: 60,
      layout: "center",
    },
    {
      id: "path",
      durationInFrames: 240,
      kicker: "课程路径",
      headline: "管理他人",
      subline: "从认识到实践，逐步构建职场竞争力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#a78bfa",
      videoStartSeconds: 48,
      layout: "path",
    },
    {
      id: "end",
      durationInFrames: 120,
      kicker: "领导他人",
      headline: "管理他人",
      subline: "系统学习，打造不可替代的职场竞争力。",
      keywords: ["职场", "领导力", "晋升"],
      accent: "#a78bfa",
      videoStartSeconds: 24,
      layout: "teacher",
    },
  ]
};

export const COURSE_PROMO_3_4_DURATION = 1110;
